# Mavlink
MAVLINK_PORT = "/dev/serial0"
MAVLINK_BAUD = 115200
MAVLINK_CONNECT_TIMEOUT = 60
MAVLINK_ARM_TIMEOUT = 120
MAVLINK_GUIDED_TIMEOUT = 60
MAVLINK_HOME_CAPTURE_TIMEOUT = 10
MAVLINK_LAND_ERROR_MAX = 0.15
