# MAVLINK
MAVLINK_PORT = "/dev/serial0"
MAVLINK_BAUD = 115200
MAVLINK_CONNECT_TIMEOUT = 60
MAVLINK_ARM_TIMEOUT = 120
MAVLINK_GUIDED_TIMEOUT = 60
MAVLINK_HOME_CAPTURE_TIMEOUT = 10
MAVLINK_HOVER_TIMEOUT = 60
MAVLINK_LAND_TIMEOUT = 60
MAVLINK_CRUISE_ALT = 5.0
CRUISE_ALT_M = MAVLINK_CRUISE_ALT


# GEOFENCE
GEOFENCE_LAT_MIN = 0.0
GEOFENCE_LAT_MAX = 0.0
GEOFENCE_LON_MIN = 0.0
GEOFENCE_LON_MAX = 0.0


# REALSENSE
CAMERA_TILT_DEG = 30
_RESOLUTIONS = {"HIGH": (1280, 720), "MED": (848, 480), "LOW": (640, 480)}
RESOLUTION = "HIGH"
FRAME_WIDTH, FRAME_HEIGHT = _RESOLUTIONS[RESOLUTION]
FPS = 30
REALSENSE_WARMUP_FRAMES = 30


# YOLO
YOLO_PATH = "best.pt"
BALL_CLASSES = {"blue": 0, "red": 1, "yellow": 2}
BARREL_CLASS_ID = 3
BALL_CONF_THRESHOLD = 0.5
BARREL_CONF_THRESHOLD = 0.5
BALL_ORDER = ["blue", "red", "yellow"]

# MISSION RULES
DROP_MIN_ALT_M = 1.5
BARREL_USED_RADIUS_M = 0.5


# GRIPPER
GRIPPER_OFFSET_X_M = 0.3
GRIPPER_OFFSET_Y_M = 0.3

# MISSION TIMING
MISSION_TIMEOUT_S = 630.0
SEARCH_TIMEOUT_S = 15.0
ALIGN_TIMEOUT_S = 10.0

# BALL PICKUP
PICKUP_ORDER = ["blue", "red", "yellow"]
INITIAL_REVERSE_M = 5.0
INITIAL_REVERSE_SPEED = 0.4
GRIP_DISTANCE_M = 0.25
GRIP_HOLD_S = 1.0
MAX_GRIP_RETRIES = 3

# GRIP VERIFICATION
GRIP_VERIFY_ENABLED = True
GRIP_VERIFY_WAIT_S = 0.5
GRIP_VERIFY_DEPTH_DELTA = 0.10

# BARREL APPROACH
BARREL_SEARCH_FWD_M = 8.0
BARREL_SEARCH_SPEED = 0.5
DROP_HOVER_M = 1.5

# VELOCITY CONTROLLER
KP_Z = 0.4
KP_XY = 0.4
MAX_SPEED_XY = 0.5
MAX_SPEED_Z = 0.3
CENTER_THRESH_M = 0.05
